// <auto-generated />
using System;
using Insight.SaveTheBees.SelfServe.WebApi.Models.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Insight.SaveTheBees.SelfServe.WebApi.Data.Migrations.ApplicationDatabase
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181105153704_AddHiveAndClusterTables")]
    partial class AddHiveAndClusterTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Insight.SaveTheBees.SelfServe.WebApi.Models.Application.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Insight.SaveTheBees.SelfServe.WebApi.Models.Application.Data.Hive", b =>
                {
                    b.Property<Guid>("HiveId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ClusterId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<Guid>("UserId");

                    b.HasKey("HiveId");

                    b.HasIndex("ClusterId");

                    b.HasIndex("UserId");

                    b.ToTable("Hives");
                });

            modelBuilder.Entity("Insight.SaveTheBees.SelfServe.WebApi.Models.Application.Data.HiveCluster", b =>
                {
                    b.Property<Guid>("ClusterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<Guid>("UserId");

                    b.HasKey("ClusterId");

                    b.HasIndex("UserId");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("Insight.SaveTheBees.SelfServe.WebApi.Models.Application.Data.Hive", b =>
                {
                    b.HasOne("Insight.SaveTheBees.SelfServe.WebApi.Models.Application.Data.HiveCluster", "Cluster")
                        .WithMany()
                        .HasForeignKey("ClusterId");

                    b.HasOne("Insight.SaveTheBees.SelfServe.WebApi.Models.Application.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Insight.SaveTheBees.SelfServe.WebApi.Models.Application.Data.HiveCluster", b =>
                {
                    b.HasOne("Insight.SaveTheBees.SelfServe.WebApi.Models.Application.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
